# Generated by Django 3.1 on 2020-09-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RIGS', '0039_auto_20200915_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='forum_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
